-- Migration V3: Add Admin Settings Structure
-- This migration adds the admin_settings table and populates it with initial configuration

-- Create admin_settings table if it doesn't exist
CREATE TABLE IF NOT EXISTS admin_settings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    key_name VARCHAR(100) NOT NULL UNIQUE,
    value TEXT NOT NULL,
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Insert initial admin settings
INSERT INTO admin_settings (key_name, value, description) VALUES
('maintenance_mode', 'false', 'Platform maintenance mode'),
('about_content', 'مرحباً بكم في منصة الاستثمار', 'About platform content in Arabic'),
('default_usage_limit', '100', 'Default referral usage limit'),
('platform_name', 'منصة الاستثمار', 'Platform name in Arabic'),
('platform_description', 'منصة استثمار آمنة وموثوقة', 'Platform description in Arabic'),
('contact_email', 'support@investment.com', 'Support email address'),
('contact_phone', '+966500000000', 'Support phone number'),
('min_withdrawal', '10.00', 'Minimum withdrawal amount'),
('max_withdrawal', '50000.00', 'Maximum withdrawal amount'),
('withdrawal_fee', '2.00', 'Withdrawal fee percentage'),
('daily_withdrawal_limit', '10000.00', 'Daily withdrawal limit'),
('min_deposit', '5.00', 'Minimum deposit amount'),
('max_deposit', '100000.00', 'Maximum deposit amount'),
('referral_direct_rate', '0.12', 'Direct referral commission rate (12%)'),
('referral_grand_rate', '0.06', 'Grand referral commission rate (6%)'),
('auto_upgrade_enabled', 'true', 'Enable automatic plan upgrades'),
('freeze_capital_on_upgrade', 'true', 'Freeze capital during plan upgrades'),
('progressive_profit_days', '30', 'Number of days for progressive profit calculation'),
('counter_duration_hours', '24', 'Daily counter duration in hours'),
('auto_completion_enabled', 'true', 'Enable automatic counter completion'),
('max_login_attempts', '5', 'Maximum login attempts before lockout'),
('lockout_duration_minutes', '30', 'Account lockout duration in minutes'),
('password_min_length', '6', 'Minimum password length'),
('session_timeout_minutes', '1440', 'Session timeout in minutes (24 hours)'),
('enable_registration', 'true', 'Enable new user registration'),
('require_email_verification', 'false', 'Require email verification for registration'),
('require_phone_verification', 'true', 'Require phone verification for registration'),
('enable_referral_system', 'true', 'Enable referral system'),
('enable_withdrawal', 'true', 'Enable withdrawal functionality'),
('enable_deposit', 'true', 'Enable deposit functionality'),
('enable_plan_purchases', 'true', 'Enable plan purchase functionality'),
('default_language', 'ar', 'Default platform language'),
('supported_languages', 'ar,en', 'Supported languages (comma-separated)'),
('timezone', 'Asia/Riyadh', 'Platform timezone'),
('date_format', 'dd/MM/yyyy', 'Date format for display'),
('time_format', 'HH:mm:ss', 'Time format for display'),
('currency_code', 'USD', 'Platform currency code'),
('currency_symbol', '$', 'Platform currency symbol'),
('decimal_places', '2', 'Number of decimal places for amounts'),
('enable_notifications', 'true', 'Enable system notifications'),
('enable_audit_logging', 'true', 'Enable audit logging'),
('enable_rate_limiting', 'true', 'Enable API rate limiting'),
('rate_limit_requests_per_minute', '60', 'API rate limit requests per minute'),
('enable_captcha', 'false', 'Enable CAPTCHA for forms'),
('enable_2fa', 'false', 'Enable two-factor authentication'),
('enable_api_documentation', 'true', 'Enable Swagger API documentation'),
('enable_health_checks', 'true', 'Enable health check endpoints'),
('enable_metrics', 'true', 'Enable application metrics'),
('log_level', 'INFO', 'Application log level'),
('enable_debug_mode', 'false', 'Enable debug mode'),
('enable_profiling', 'false', 'Enable application profiling'),
('enable_caching', 'true', 'Enable application caching'),
('cache_ttl_seconds', '3600', 'Cache time-to-live in seconds'),
('enable_compression', 'true', 'Enable response compression'),
('enable_ssl', 'false', 'Enable SSL/TLS'),
('enable_cors', 'true', 'Enable CORS support'),
('allowed_origins', 'https://yourdomain.com,http://localhost:3000', 'Allowed CORS origins'),
('enable_security_headers', 'true', 'Enable security headers'),
('enable_csrf_protection', 'true', 'Enable CSRF protection'),
('enable_xss_protection', 'true', 'Enable XSS protection'),
('enable_content_security_policy', 'true', 'Enable Content Security Policy'),
('enable_hsts', 'true', 'Enable HTTP Strict Transport Security'),
('enable_frame_options', 'true', 'Enable X-Frame-Options header'),
('enable_content_type_options', 'true', 'Enable X-Content-Type-Options header'),
('enable_referrer_policy', 'true', 'Enable Referrer-Policy header'),
('enable_permissions_policy', 'true', 'Enable Permissions-Policy header');

-- Create index for better performance
CREATE INDEX idx_admin_settings_key ON admin_settings(key_name); 