"use client"

import React, { createContext, useContext, useEffect, useState } from 'react'

type Language = 'en' | 'ar'

interface LanguageContextType {
  language: Language
  toggleLanguage: () => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translation dictionary
const translations = {
  en: {
    // Dashboard
    'dashboard': 'Dashboard',
    'welcome': 'Welcome',
    'total_balance': 'Total Balance',
    'daily_profit': 'Daily Profit',
    'activate_timer': 'Activate Timer',
    'complete_timer': 'Complete Timer',
    'choose_plan': 'Choose a Plan',
    'timer_active': 'Timer Active',
    'timer_completed': 'Timer Completed',
    'start_new_timer': 'Start New Timer',
    'daily_timer': 'Daily Timer',
    'current_plan': 'Current Plan',
    'no_active_plan': 'No active plan',
    'claim_profit': 'Claim Profit',
    'claiming': 'Claiming...',
    'activating': 'Activating...',
    'timer_active_status': 'Timer Active',
    'come_back_later': 'Come back when the timer completes!',
    'ready_to_claim': 'Ready to Claim!',
    'countdown': 'Countdown',
    
    // Navigation
    'profile': 'Profile',
    'deposit': 'Deposit',
    'withdraw': 'Withdraw',
    'referrals': 'Referrals',
    'plans': 'Plans',
    'wallet': 'Wallet',
    'logout': 'Logout',
    'back_to_dashboard': 'Back to Dashboard',
    
    // Plans
    'investment_plans': 'Investment Plans',
    'choose_your_plan': 'Choose Your Investment Plan',
    'select_perfect_plan': 'Select the perfect investment plan that matches your goals.',
    'investment_range': 'Investment Range',
    'duration': 'Duration',
    'daily_profit': 'Daily Profit',
    'total_profit': 'Total Profit',
    'invest_now': 'Invest Now',
    'most_popular': 'Most Popular',
    'level': 'Level',
    'investment_amount': 'Investment Amount',
    'daily_profit_range': 'Daily Profit Range',
    'avg': 'Avg',
    'monthly_profit': 'Monthly Profit',
    'return': 'Return',
    'plan_level': 'Plan Level',
    'investment': 'Investment',
    'demo_mode': 'Demo Mode',
    'no_plans_available': 'No plans available at the moment.',
    'how_investment_works': 'How Investment Works',
    'understanding_investment_process': 'Understanding the investment process',
    'choose_your_plan_step': 'Choose Your Plan',
    'choose_plan_description': 'Select an investment plan that matches your goals and budget',
    'make_deposit_step': 'Make Your Deposit',
    'make_deposit_description': 'Deposit your investment amount using secure payment methods',
    'earn_daily_profits_step': 'Earn Daily Profits',
    'earn_daily_profits_description': 'Receive daily profit distributions directly to your account',
    'withdraw_anytime_step': 'Withdraw Anytime',
    'withdraw_anytime_description': 'Withdraw your profits or reinvest for compound growth',
    'investment_benefits': 'Investment Benefits',
    'why_choose_platform': 'Why choose our investment platform',
    'high_returns': 'High Returns',
    'high_returns_description': 'Competitive daily profit rates with transparent calculations',
    'daily_payouts': 'Daily Payouts',
    'daily_payouts_description': 'Receive your profits daily, not monthly or yearly',
    'flexible_terms': 'Flexible Terms',
    'flexible_terms_description': 'Choose from various investment amounts and profit levels',
    'ready_to_start': 'Ready to Start Investing?',
    'join_thousands': 'Join thousands of investors who are already earning daily profits. Start your investment journey today with our secure and transparent platform.',
    'start_investing_now': 'Start Investing Now',
    'refresh': 'Refresh',
    'new_deposit': 'New Deposit',
    'choose_plan_deposit': 'Choose a plan and enter deposit amount',
    'investment_plan': 'Investment Plan',
    'amount_usd': 'Amount (USD)',
    'promo_code': 'Promo Code (Optional)',
    'enter_promo_code': 'Enter promo code',
    'submit_deposit': 'Submit Deposit',
    'plan_details': 'Plan Details',
    'plan_features': 'Plan Features',
    
    // Referrals
    'referral_network': 'Referral Network',
    'total_referrals': 'Total Referrals',
    'direct_referrals': 'Direct Referrals',
    'second_level': 'Second Level',
    'total_earnings': 'Total Earnings',
    'your_referral_code': 'Your Referral Code',
    'share_referral_code_description': 'Share your referral code with friends and earn up to 12% commission on their deposits',
    'referral_code': 'Referral Code',
    'referral_link': 'Referral Link',
    'how_it_works': 'How it works',
    'share_referral_code_step': 'Share your referral code with friends',
    'they_register_step': 'They register using your code',
    'earn_12_percent_step': 'You earn 12% commission on their deposits (Direct)',
    'earn_6_percent_step': 'You earn 6% commission on their referrals\' deposits (Second Level)',
    'commissions_paid_instantly': 'Commissions are paid instantly',
    'your_referrals': 'Your Referrals',
    'view_referrals_description': 'View all users who registered using your referral code',
    'no_referrals_yet': 'No Referrals Yet',
    'start_sharing_referral_code': 'Start sharing your referral code to earn commissions!',
    'user': 'User',
    'status': 'Status',
    'joined': 'Joined',
    'total_deposits': 'Total Deposits',
    'commission_earned': 'Commission Earned',
    'copied': 'Copied!',
    'referral_code_copied': 'Referral code copied to clipboard',
    'referral_link_copied': 'Referral link copied to clipboard',
    'active': 'Active',
    'inactive': 'Inactive',
    'pending': 'Pending',
    'failed_to_load_referral_data': 'Failed to load referral data from database. Showing demo data.',
    'failed_to_load_referral_data_retry': 'Failed to load referral data. Please try again later.',
    'total_amount': 'Total Amount',
    'todays_profit': 'Today\'s Profit',
    'about': 'About',
    'transactions': 'Transactions',
    'need_active_plan_message': 'You need an active investment plan to start earning daily profits.',
    'daily_profit_distribution': 'Daily profit distribution',
    'support_24_7': '24/7 support',
    'secure_transactions': 'Secure transactions',
    'instant_activation': 'Instant activation',
    'deposit_information': 'Deposit Information',
    'minimum_deposit': 'Minimum Deposit',
    'maximum_deposit': 'Maximum Deposit',
    'processing_time': 'Processing Time',
    'instant': 'Instant',
    'withdraw_funds': 'Withdraw Funds',
    'withdraw_earnings': 'Withdraw your earnings to your USDT wallet',
    'withdrawal_fee_info': 'Withdrawal Fee Information',
    'fee_percentage': '12% fee will be deducted',
    'fee_calculation': 'Fee Calculation',
    'requested_amount': 'Requested Amount',
    'fee_amount': 'Fee (12%)',
    'net_amount': 'Net Amount (You will receive)',
    'fee_note': 'A 12% processing fee will be deducted from your withdrawal amount.',
    'enter_withdrawal_amount': 'Enter withdrawal amount',
    'usdt_wallet_address': 'USDT Wallet Address',
    'submit_withdrawal': 'Submit Withdrawal',
    'wallet_management': 'Wallet Management',
    'save_wallet_address': 'Save your USDT wallet address for future withdrawals',
    'no_wallet_address': 'No Wallet Address Set',
    'please_save_wallet': 'Please save your USDT wallet address to enable withdrawals.',
    'new_wallet_address': 'New Wallet Address',
    'save_wallet_address_btn': 'Save Wallet Address',
    'important_notes': 'Important Notes',
    'min_withdrawal': 'Minimum withdrawal amount: $10',
    'max_withdrawal': 'Maximum withdrawal amount: $50,000',
    'withdrawal_processing_time': 'Withdrawal processing time: 24-48 hours',
    'only_usdt_accepted': 'Only USDT (TRC20) wallet addresses are accepted',
    'verify_wallet_address': 'Make sure your wallet address is correct before submitting',
    'withdrawal_history': 'Withdrawal History',
    'transaction_history': 'Transaction History',
    'view_withdrawal_requests': 'View all your withdrawal requests and their current status',
    'no_withdrawals_yet': 'No Withdrawals Yet',
    'no_withdrawal_requests': 'You haven\'t made any withdrawal requests yet.',
    'make_first_withdrawal': 'Make Your First Withdrawal',
    'referral_code': 'Referral Code',
    'bonus_profit': 'Bonus Profit',
    'home': 'Home',
    'investment': 'Investment',
    'wallet': 'Wallet',
    'wallet_settings': 'Wallet Settings',
    'your_wallet_address': 'Your wallet address for withdrawals',
    'need_set_wallet': 'You need to set your USDT wallet address to receive withdrawals.',
    'usdt_wallet_address_trc20': 'USDT Wallet Address (TRC20)',
    'network_information': 'Network Information',
    'network': 'Network',
    'token': 'Token',
    'network_notes': 'Important Notes:',
    'only_trc20_supported': 'Only USDT (TRC20) network is supported',
    'ensure_correct_network': 'Ensure you\'re using the correct network',
    'double_check_address': 'Double-check the address before saving',
    'withdrawals_sent_to': 'Withdrawals will be sent to this address',
    'quick_actions': 'Quick Actions',
    'make_withdrawal': 'Make Withdrawal',
    'view_withdrawal_history': 'View Withdrawal History',
    'security_tips': 'Security Tips',
    'verify_address_before_saving': 'Always verify the wallet address before saving',
    'use_own_wallet': 'Use only your own wallet address',
    'keep_credentials_secure': 'Keep your wallet credentials secure',
    'never_share_private_keys': 'Never share your private keys',
    'personal_information': 'Personal Information',
    'account_details': 'Your account details and preferences',
    'full_name': 'Full Name',
    'username_label': 'Username',
    'phone_number': 'Phone Number',
    'account_status': 'Account Status',
    'member_since': 'Member Since',
    'last_login': 'Last Login',
    'investment_activity': 'Your investment activity summary',
    'min_max': 'Min: $60 | Max: $600',
    'min_max_withdrawal': 'Min: $10 | Max: $50,000',
    'select_plan': 'Select a plan',
    
    // Balance related
    'account_balance': 'Account Balance',
    'account_balance_description': 'Your current account balance information',
    'withdrawable_balance': 'Withdrawable Balance',
    'available_for_withdrawal': 'Available for withdrawal',
    'frozen_balance': 'Frozen Balance',
    'investment_capital_locked': 'Investment capital (locked)',
    'total_balance': 'Total Balance',
    'total_account_value': 'Total account value',
    'referral_earnings': 'Referral Earnings',
    'from_referrals': 'From referrals',
    'max': 'Max',
    'withdrawal_limits': 'Withdrawal Limits',
    'no_withdrawable_balance': 'No Withdrawable Balance',
    'no_withdrawable_balance_message': 'You need to earn profits from your investment plan before you can make withdrawals. The withdrawable balance shows only your profits, not your investment capital.',
    
    // Profile
    'account_information': 'Account Information',
    'edit_profile': 'Edit Profile',
    'save_changes': 'Save Changes',
    'cancel': 'Cancel',
    'account_statistics': 'Account Statistics',
    'total_deposits': 'Total Deposits',
    'total_withdrawals': 'Total Withdrawals',
    'total_profits': 'Total Profits',
    'make_deposit': 'Make Deposit',
    'withdraw_funds': 'Withdraw Funds',
    'view_referrals': 'View Referrals',
    
    // Common
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'close': 'Close',
    'next': 'Next',
    'previous': 'Previous',
    'submit': 'Submit',
    'reset': 'Reset',
    'search': 'Search',
    'filter': 'Filter',
    'sort': 'Sort',
    'copy': 'Copy',
    'copied': 'Copied!',
    
    // Status
    'active': 'Active',
    'pending': 'Pending',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'approved': 'Approved',
    'rejected': 'Rejected',
    'processing': 'Processing',
    
    // Time
    'days': 'days',
    'hours': 'hours',
    'minutes': 'minutes',
    'seconds': 'seconds',
    
    // Currency
    'currency': '$',
    
    // Messages
    'no_data_available': 'No data available',
    'try_again_later': 'Please try again later',
    'operation_successful': 'Operation completed successfully',
    'operation_failed': 'Operation failed',
    'network_error': 'Network error occurred',
    'unauthorized': 'Unauthorized access',
    'forbidden': 'Access forbidden',
    'not_found': 'Resource not found',
    'server_error': 'Server error occurred',
    

    
    // Deposit Page - Additional translations
    'plan_details': 'Plan Details',
    'daily_profit_label': 'Daily Profit',
    'duration_label': 'Duration',
    'monthly_profit_label': 'Monthly Profit',
    'plan_features_label': 'Plan Features:',
    'daily_profit_distribution': 'Daily profit distribution',
    'support_24_7': '24/7 support',
    'secure_transactions': 'Secure transactions',
    'instant_activation': 'Instant activation',
    'admin_trc20_address': 'Admin TRC20 Address',
    'send_deposit_to_address': 'Send your deposit to this USDT (TRC20) address',
    'usdt_trc20_address': 'USDT (TRC20) Address:',
    'copy': 'Copy',
    'important_notes_label': 'Important Notes:',
    'only_send_usdt_trc20': 'Only send USDT (TRC20) to this address',
    'double_check_address': 'Double-check the address before sending',
    'deposits_processed_automatically': 'Deposits are processed automatically',
    'contact_support_wrong_address': 'Contact support if you send to wrong address',
    'scan_qr_code': 'Scan QR Code',
    'scan_qr_description': 'Scan this QR code with your wallet app for quick deposit',
    'usdt_deposit_qr_code': 'USDT Deposit QR Code',
    'how_to_use': 'How to use:',
    'open_usdt_wallet': 'Open your USDT wallet app',
    'tap_send_transfer': 'Tap "Send" or "Transfer"',
    'scan_qr_code_step': 'Scan this QR code',
    'enter_deposit_amount': 'Enter the deposit amount',
    'confirm_transaction': 'Confirm the transaction',
    'tip_trc20_network': 'Tip: Make sure your wallet supports TRC20 network for USDT transfers',
    'deposit_information': 'Deposit Information',
    'minimum_deposit': 'Minimum Deposit',
    'maximum_deposit': 'Maximum Deposit',
    'processing_time': 'Processing Time',
    'instant': 'Instant',
    'admin_address_copied': 'Admin TRC20 address copied to clipboard',
    
    // Withdrawal History Page - Additional translations
    'withdrawal_history': 'Withdrawal History',
    'transaction_history': 'Transaction History',
    'view_withdrawal_requests': 'View all your withdrawal requests and their current status',
    'no_withdrawals_yet': 'No Withdrawals Yet',
    'no_withdrawal_requests': 'You haven\'t made any withdrawal requests yet.',
    'make_first_withdrawal': 'Make Your First Withdrawal',
    'statistics': 'Statistics',
    'total_withdrawals': 'Total Withdrawals',
    'total_amount': 'Total Amount',
    'pending': 'Pending',
    'completed': 'Completed',
    'id': 'ID',
    'amount': 'Amount',
    'status': 'Status',
    'wallet_address': 'Wallet Address',
    'created': 'Created',
    'processed': 'Processed',
    'transaction': 'Transaction',
    'failed_to_load_withdrawal_data': 'Failed to load withdrawal history from database. Showing demo data.',
    'failed_to_load_withdrawal_data_retry': 'Failed to load withdrawal history. Please try again later.',
  },
  ar: {
    // Dashboard
    'dashboard': 'لوحة التحكم',
    'welcome': 'مرحباً',
    'total_balance': 'الرصيد الإجمالي',
    'daily_profit': 'الربح اليومي',
    'activate_timer': 'تفعيل المؤقت',
    'complete_timer': 'إكمال المؤقت',
    'choose_plan': 'اختر خطة',
    'timer_active': 'المؤقت نشط',
    'timer_completed': 'تم إكمال المؤقت',
    'start_new_timer': 'بدء مؤقت جديد',
    'daily_timer': 'المؤقت اليومي',
    'current_plan': 'الخطة الحالية',
    'no_active_plan': 'لا توجد خطة نشطة',
    'claim_profit': 'استلام الربح',
    'claiming': 'جاري الاستلام...',
    'activating': 'جاري التفعيل...',
    'timer_active_status': 'المؤقت نشط',
    'come_back_later': 'عد عندما يكتمل المؤقت!',
    'ready_to_claim': 'جاهز للاستلام!',
    'countdown': 'العد التنازلي',
    
    // Navigation
    'profile': 'الملف الشخصي',
    'deposit': 'إيداع',
    'withdraw': 'سحب',
    'referrals': 'الإحالات',
    'plans': 'الخطط',
    'wallet': 'المحفظة',
    'logout': 'تسجيل الخروج',
    'back_to_dashboard': 'العودة للوحة التحكم',
    
    // Plans
    'investment_plans': 'خطط الاستثمار',
    'choose_your_plan': 'اختر خطة الاستثمار الخاصة بك',
    'select_perfect_plan': 'اختر خطة الاستثمار المثالية التي تناسب أهدافك.',
    'investment_range': 'نطاق الاستثمار',
    'duration': 'المدة',
    'daily_profit': 'الربح اليومي',
    'total_profit': 'الربح الإجمالي',
    'invest_now': 'استثمر الآن',
    'most_popular': 'الأكثر شعبية',
    'level': 'المستوى',
    'investment_amount': 'مبلغ الاستثمار',
    'daily_profit_range': 'نطاق الربح اليومي',
    'avg': 'متوسط',
    'monthly_profit': 'الربح الشهري',
    'return': 'العائد',
    'plan_level': 'مستوى الخطة',
    'investment': 'الاستثمار',
    'demo_mode': 'وضع العرض',
    'no_plans_available': 'لا توجد خطط متاحة في الوقت الحالي.',
    'how_investment_works': 'كيف يعمل الاستثمار',
    'understanding_investment_process': 'فهم عملية الاستثمار',
    'choose_your_plan_step': 'اختر خطتك',
    'choose_plan_description': 'اختر خطة استثمار تناسب أهدافك وميزانيتك',
    'make_deposit_step': 'أجرِ إيداعك',
    'make_deposit_description': 'أودع مبلغ استثمارك باستخدام طرق دفع آمنة',
    'earn_daily_profits_step': 'اكسب أرباح يومية',
    'earn_daily_profits_description': 'احصل على توزيعات الأرباح اليومية مباشرة إلى حسابك',
    'withdraw_anytime_step': 'اسحب في أي وقت',
    'withdraw_anytime_description': 'اسحب أرباحك أو أعد استثمارها للنمو المركب',
    'investment_benefits': 'مزايا الاستثمار',
    'why_choose_platform': 'لماذا تختار منصتنا الاستثمارية',
    'high_returns': 'عوائد عالية',
    'high_returns_description': 'معدلات ربح يومية تنافسية مع حسابات شفافة',
    'daily_payouts': 'مدفوعات يومية',
    'daily_payouts_description': 'احصل على أرباحك يومياً، وليس شهرياً أو سنوياً',
    'flexible_terms': 'شروط مرنة',
    'flexible_terms_description': 'اختر من مبالغ استثمارية ومستويات ربح متنوعة',
    'ready_to_start': 'هل أنت مستعد لبدء الاستثمار؟',
    'join_thousands': 'انضم إلى آلاف المستثمرين الذين يكسبون أرباحاً يومية بالفعل. ابدأ رحلة استثمارك اليوم مع منصتنا الآمنة والشفافة.',
    'start_investing_now': 'ابدأ الاستثمار الآن',
    'refresh': 'تحديث',
    'new_deposit': 'إيداع جديد',
    'choose_plan_deposit': 'اختر خطة وأدخل مبلغ الإيداع',
    'investment_plan': 'خطة الاستثمار',
    'amount_usd': 'المبلغ (دولار أمريكي)',
    'promo_code': 'رمز ترويجي (اختياري)',
    'enter_promo_code': 'أدخل الرمز الترويجي',
    'submit_deposit': 'إرسال الإيداع',
    'plan_details': 'تفاصيل الخطة',
    'plan_features': 'ميزات الخطة',
    
    // Referrals
    'referral_network': 'شبكة الإحالات',
    'total_referrals': 'إجمالي الإحالات',
    'direct_referrals': 'الإحالات المباشرة',
    'second_level': 'المستوى الثاني',
    'total_earnings': 'إجمالي الأرباح',
    'your_referral_code': 'رمز الإحالة الخاص بك',
    'share_referral_code_description': 'شارك رمز الإحالة الخاص بك مع الأصدقاء واكسب عمولة تصل إلى 12% على إيداعاتهم',
    'referral_code': 'رمز الإحالة',
    'referral_link': 'رابط الإحالة',
    'how_it_works': 'كيف يعمل',
    'share_referral_code_step': 'شارك رمز الإحالة الخاص بك مع الأصدقاء',
    'they_register_step': 'يسجلون باستخدام رمزك',
    'earn_12_percent_step': 'تكسب عمولة 12% على إيداعاتهم (مباشر)',
    'earn_6_percent_step': 'تكسب عمولة 6% على إيداعات إحالاتهم (المستوى الثاني)',
    'commissions_paid_instantly': 'يتم دفع العمولات فوراً',
    'your_referrals': 'إحالاتك',
    'view_referrals_description': 'عرض جميع المستخدمين الذين سجلوا باستخدام رمز الإحالة الخاص بك',
    'no_referrals_yet': 'لا توجد إحالات بعد',
    'start_sharing_referral_code': 'ابدأ بمشاركة رمز الإحالة الخاص بك لربح العمولات!',
    'user': 'المستخدم',
    'status': 'الحالة',
    'joined': 'انضم',
    'total_deposits': 'إجمالي الإيداعات',
    'commission_earned': 'العمولة المكتسبة',
    'copied': 'تم النسخ!',
    'referral_code_copied': 'تم نسخ رمز الإحالة إلى الحافظة',
    'referral_link_copied': 'تم نسخ رابط الإحالة إلى الحافظة',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'pending': 'قيد الانتظار',
    'failed_to_load_referral_data': 'فشل في تحميل بيانات الإحالة من قاعدة البيانات. عرض بيانات تجريبية.',
    'failed_to_load_referral_data_retry': 'فشل في تحميل بيانات الإحالة. يرجى المحاولة مرة أخرى لاحقاً.',
    'total_amount': 'إجمالي المبلغ',
    'todays_profit': 'ربح اليوم',
    'about': 'حول',
    'transactions': 'المعاملات',
    'need_active_plan_message': 'تحتاج إلى خطة استثمار نشطة لبدء كسب الأرباح اليومية.',
    'daily_profit_distribution': 'توزيع الأرباح اليومية',
    'support_24_7': 'دعم على مدار الساعة',
    'secure_transactions': 'معاملات آمنة',
    'instant_activation': 'تفعيل فوري',
    'deposit_information': 'معلومات الإيداع',
    'minimum_deposit': 'الحد الأدنى للإيداع',
    'maximum_deposit': 'الحد الأقصى للإيداع',
    'processing_time': 'وقت المعالجة',
    'instant': 'فوري',
    'withdraw_funds': 'سحب الأموال',
    'withdraw_earnings': 'اسحب أرباحك إلى محفظة USDT الخاصة بك',
    'withdrawal_fee_info': 'معلومات رسوم السحب',
    'fee_percentage': 'سيتم خصم رسوم 12%',
    'fee_calculation': 'حساب الرسوم',
    'requested_amount': 'المبلغ المطلوب',
    'fee_amount': 'الرسوم (12%)',
    'net_amount': 'المبلغ الصافي (ستحصل عليه)',
    'fee_note': 'سيتم خصم رسوم معالجة 12% من مبلغ السحب.',
    'enter_withdrawal_amount': 'أدخل مبلغ السحب',
    'usdt_wallet_address': 'عنوان محفظة USDT',
    'submit_withdrawal': 'إرسال السحب',
    'wallet_management': 'إدارة المحفظة',
    'save_wallet_address': 'احفظ عنوان محفظة USDT الخاصة بك للسحوبات المستقبلية',
    'no_wallet_address': 'لم يتم تعيين عنوان محفظة',
    'please_save_wallet': 'يرجى حفظ عنوان محفظة USDT الخاصة بك لتمكين السحوبات.',
    'new_wallet_address': 'عنوان محفظة جديد',
    'save_wallet_address_btn': 'حفظ عنوان المحفظة',
    'important_notes': 'ملاحظات مهمة',
    'min_withdrawal': 'الحد الأدنى لمبلغ السحب: 10 دولار',
    'max_withdrawal': 'الحد الأقصى لمبلغ السحب: 50,000 دولار',
    'withdrawal_processing_time': 'وقت معالجة السحب: 24-48 ساعة',
    'only_usdt_accepted': 'يتم قبول عناوين محافظ USDT (TRC20) فقط',
    'verify_wallet_address': 'تأكد من صحة عنوان المحفظة قبل الإرسال',
    'withdrawal_history': 'تاريخ السحوبات',
    'transaction_history': 'تاريخ المعاملات',
    'view_withdrawal_requests': 'عرض جميع طلبات السحب وحالتها الحالية',
    'no_withdrawals_yet': 'لا توجد سحوبات بعد',
    'no_withdrawal_requests': 'لم تقم بأي طلبات سحب بعد.',
    'make_first_withdrawal': 'أجرِ أول سحب لك',
    'referral_code': 'رمز الإحالة',
    'bonus_profit': 'ربح إضافي',
    'home': 'الرئيسية',
    'investment': 'الاستثمار',
    'wallet': 'المحفظة',
    'wallet_settings': 'إعدادات المحفظة',
    'your_wallet_address': 'عنوان محفظتك للسحوبات',
    'need_set_wallet': 'تحتاج إلى تعيين عنوان محفظة USDT الخاصة بك لاستلام السحوبات.',
    'usdt_wallet_address_trc20': 'عنوان محفظة USDT (TRC20)',
    'network_information': 'معلومات الشبكة',
    'network': 'الشبكة',
    'token': 'الرمز المميز',
    'network_notes': 'ملاحظات مهمة:',
    'only_trc20_supported': 'يتم دعم شبكة USDT (TRC20) فقط',
    'ensure_correct_network': 'تأكد من استخدام الشبكة الصحيحة',
    'double_check_address': 'تحقق من العنوان مرتين قبل الحفظ',
    'withdrawals_sent_to': 'سيتم إرسال السحوبات إلى هذا العنوان',
    'quick_actions': 'إجراءات سريعة',
    'make_withdrawal': 'إجراء سحب',
    'view_withdrawal_history': 'عرض تاريخ السحوبات',
    'security_tips': 'نصائح الأمان',
    'verify_address_before_saving': 'تحقق دائماً من عنوان المحفظة قبل الحفظ',
    'use_own_wallet': 'استخدم عنوان محفظتك الخاصة فقط',
    'keep_credentials_secure': 'احتفظ ببيانات اعتماد محفظتك آمنة',
    'never_share_private_keys': 'لا تشارك مفاتيحك الخاصة أبداً',
    'personal_information': 'المعلومات الشخصية',
    'account_details': 'تفاصيل حسابك وتفضيلاتك',
    'full_name': 'الاسم الكامل',
    'username_label': 'اسم المستخدم',
    'phone_number': 'رقم الهاتف',
    'account_status': 'حالة الحساب',
    'member_since': 'عضو منذ',
    'last_login': 'آخر تسجيل دخول',
    'investment_activity': 'ملخص نشاطك الاستثماري',
    'min_max': 'الحد الأدنى: 60 دولار | الحد الأقصى: 600 دولار',
    'min_max_withdrawal': 'الحد الأدنى: 10 دولار | الحد الأقصى: 50,000 دولار',
    'select_plan': 'اختر خطة',
    
    // Balance related
    'account_balance': 'رصيد الحساب',
    'account_balance_description': 'معلومات رصيد حسابك الحالي',
    'withdrawable_balance': 'رصيد قابل للسحب',
    'available_for_withdrawal': 'متاح للسحب',
    'frozen_balance': 'رصيد مجمد',
    'investment_capital_locked': 'رأس المال الاستثماري (مقفل)',
    'total_balance': 'الرصيد الإجمالي',
    'total_account_value': 'قيمة الحساب الإجمالية',
    'referral_earnings': 'أرباح الإحالة',
    'from_referrals': 'من الإحالات',
    'max': 'الحد الأقصى',
    'withdrawal_limits': 'حدود السحب',
    'no_withdrawable_balance': 'لا يوجد رصيد قابل للسحب',
    'no_withdrawable_balance_message': 'يجب أن تكسب الأرباح من خطة الاستثمار الخاصة بك قبل أن تتمكن من إجراء السحوبات. يظهر رصيد قابل للسحب فقط الأرباح، وليس رأس المال الاستثماري.',
    
    // Profile
    'account_information': 'معلومات الحساب',
    'edit_profile': 'تعديل الملف الشخصي',
    'save_changes': 'حفظ التغييرات',
    'cancel': 'إلغاء',
    'account_statistics': 'إحصائيات الحساب',
    'total_deposits': 'إجمالي الإيداعات',
    'total_withdrawals': 'إجمالي السحوبات',
    'total_profits': 'إجمالي الأرباح',
    'make_deposit': 'إجراء إيداع',
    'withdraw_funds': 'سحب الأموال',
    'view_referrals': 'عرض الإحالات',
    
    // Common
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'نجح',
    'save': 'حفظ',
    'edit': 'تعديل',
    'delete': 'حذف',
    'confirm': 'تأكيد',
    'close': 'إغلاق',
    'next': 'التالي',
    'previous': 'السابق',
    'submit': 'إرسال',
    'reset': 'إعادة تعيين',
    'search': 'بحث',
    'filter': 'تصفية',
    'sort': 'ترتيب',
    'copy': 'نسخ',
    'copied': 'تم النسخ!',
    
    // Status
    'active': 'نشط',
    'pending': 'قيد الانتظار',
    'completed': 'مكتمل',
    'cancelled': 'ملغي',
    'approved': 'موافق عليه',
    'rejected': 'مرفوض',
    'processing': 'قيد المعالجة',
    
    // Time
    'days': 'أيام',
    'hours': 'ساعات',
    'minutes': 'دقائق',
    'seconds': 'ثواني',
    
    // Currency
    'currency': '$',
    
    // Messages
    'no_data_available': 'لا توجد بيانات متاحة',
    'try_again_later': 'يرجى المحاولة مرة أخرى لاحقاً',
    'operation_successful': 'تم إكمال العملية بنجاح',
    'operation_failed': 'فشلت العملية',
    'network_error': 'حدث خطأ في الشبكة',
    'unauthorized': 'وصول غير مصرح',
    'forbidden': 'الوصول ممنوع',
    'not_found': 'المورد غير موجود',
    'server_error': 'حدث خطأ في الخادم',
    

    
    // Deposit Page - Additional translations
    'plan_details': 'تفاصيل الخطة',
    'daily_profit_label': 'الربح اليومي',
    'duration_label': 'المدة',
    'monthly_profit_label': 'الربح الشهري',
    'plan_features_label': 'ميزات الخطة:',
    'daily_profit_distribution': 'توزيع الأرباح اليومية',
    'support_24_7': 'دعم على مدار الساعة',
    'secure_transactions': 'معاملات آمنة',
    'instant_activation': 'تفعيل فوري',
    'admin_trc20_address': 'عنوان TRC20 للمدير',
    'send_deposit_to_address': 'أرسل إيداعك إلى عنوان USDT (TRC20) هذا',
    'usdt_trc20_address': 'عنوان USDT (TRC20):',
    'copy': 'نسخ',
    'important_notes_label': 'ملاحظات مهمة:',
    'only_send_usdt_trc20': 'أرسل USDT (TRC20) فقط إلى هذا العنوان',
    'double_check_address': 'تحقق من العنوان مرتين قبل الإرسال',
    'deposits_processed_automatically': 'يتم معالجة الإيداعات تلقائياً',
    'contact_support_wrong_address': 'تواصل مع الدعم إذا أرسلت إلى عنوان خاطئ',
    'scan_qr_code': 'مسح رمز QR',
    'scan_qr_description': 'امسح رمز QR هذا بتطبيق محفظتك للإيداع السريع',
    'usdt_deposit_qr_code': 'رمز QR لإيداع USDT',
    'how_to_use': 'كيفية الاستخدام:',
    'open_usdt_wallet': 'افتح تطبيق محفظة USDT الخاصة بك',
    'tap_send_transfer': 'اضغط "إرسال" أو "تحويل"',
    'scan_qr_code_step': 'امسح رمز QR هذا',
    'enter_deposit_amount': 'أدخل مبلغ الإيداع',
    'confirm_transaction': 'أكد المعاملة',
    'tip_trc20_network': 'نصيحة: تأكد من أن محفظتك تدعم شبكة TRC20 لتحويلات USDT',
    'deposit_information': 'معلومات الإيداع',
    'minimum_deposit': 'الحد الأدنى للإيداع',
    'maximum_deposit': 'الحد الأقصى للإيداع',
    'processing_time': 'وقت المعالجة',
    'instant': 'فوري',
    'admin_address_copied': 'تم نسخ عنوان TRC20 للمدير إلى الحافظة',
    
    // Withdrawal History Page - Additional translations
    'withdrawal_history': 'تاريخ السحوبات',
    'transaction_history': 'تاريخ المعاملات',
    'view_withdrawal_requests': 'عرض جميع طلبات السحب وحالتها الحالية',
    'no_withdrawals_yet': 'لا توجد سحوبات بعد',
    'no_withdrawal_requests': 'لم تقم بأي طلبات سحب بعد.',
    'make_first_withdrawal': 'أجرِ أول سحب لك',
    'statistics': 'الإحصائيات',
    'total_withdrawals': 'إجمالي السحوبات',
    'total_amount': 'إجمالي المبلغ',
    'pending': 'قيد الانتظار',
    'completed': 'مكتمل',
    'id': 'المعرف',
    'amount': 'المبلغ',
    'status': 'الحالة',
    'wallet_address': 'عنوان المحفظة',
    'created': 'تم الإنشاء',
    'processed': 'تم المعالجة',
    'transaction': 'المعاملة',
    'failed_to_load_withdrawal_data': 'فشل في تحميل تاريخ السحوبات من قاعدة البيانات. عرض بيانات تجريبية.',
    'failed_to_load_withdrawal_data_retry': 'فشل في تحميل تاريخ السحوبات. يرجى المحاولة مرة أخرى لاحقاً.',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  useEffect(() => {
    // Get language from localStorage or default to English
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage) {
      setLanguage(savedLanguage)
      document.documentElement.dir = savedLanguage === 'ar' ? 'rtl' : 'ltr'
      document.documentElement.lang = savedLanguage
    } else {
      // Default to English
      setLanguage('en')
      document.documentElement.dir = 'ltr'
      document.documentElement.lang = 'en'
    }
  }, [])

  const toggleLanguage = () => {
    const newLanguage = language === 'en' ? 'ar' : 'en'
    setLanguage(newLanguage)
    localStorage.setItem('language', newLanguage)
    document.documentElement.dir = newLanguage === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.lang = newLanguage
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 
